#!/usr/bin/env python3
"""Exact BQGEULER-004 two-mode hierarchical wave convergence audit."""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction as F
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]


def load(path: str) -> dict:
    return json.loads((ROOT / path).read_text())


manifest = json.loads((HERE / "INPUT_MANIFEST.json").read_text())
hash_checks = {}
for rel, expected in manifest["inputs"].items():
    actual = hashlib.sha256((ROOT / rel).read_bytes()).hexdigest()
    hash_checks[rel] = {"expected": expected, "actual": actual, "pass": actual == expected}
assert all(item["pass"] for item in hash_checks.values())

paths = list(manifest["inputs"])
bgce452 = load(paths[0])
bgce456 = load(paths[1])
bqgadm011 = load(paths[2])
bqgeuler001 = load(paths[3])
bqgeuler002 = load(paths[4])

assert bgce452["gate_decision"]["exact_multiresolution_intertwiner"] == "PASS"
assert bgce452["gate_decision"]["UCP_heat_all_depths"] == "PASS"
assert bgce456["gate_decision"]["all_depth_refinement_intertwining"] == "PASS"
assert bgce456["gate_decision"]["same_operator_positive_selfadjoint_wave"] == "PASS"
assert bqgadm011["continuum_packet"]["physical_configuration_modes_per_spatial_point"] == 2
assert bqgeuler001["work_package_status_after_gate"] == "OPEN_SOURCE_CONSTRUCTION_REQUIRED"
assert bqgeuler002["work_package_status_after_gate"] == "OPEN_SOURCE_CONSTRUCTION_REQUIRED"

alpha = F(bgce456["wave_and_spectral_theorem"]["exact_rational_form_bounds"]["alpha"])
beta = F(bgce456["wave_and_spectral_theorem"]["exact_rational_form_bounds"]["beta"])
assert 0 < alpha <= beta

# Exact convergence witness.  On level k choose, in each of two polarization
# slots, q_k=25^{-k} and p_k=5^{-k}.  The isotropic energy per polarization is
# 25^k q_k^2+p_k^2=2*25^{-k}; for two slots it is 4*25^{-k}.
# The infinite energy tail beyond m is therefore (1/6)*25^{-m} exactly.
tail_witness = []
for m in range(0, 9):
    isotropic_tail_squared = F(1, 6) * F(1, 25) ** m
    anisotropic_upper_tail_squared = (beta + 1) * F(1, 12) * F(1, 25) ** m
    tail_witness.append({
        "level": m,
        "two_polarization_isotropic_energy_error_squared": str(isotropic_tail_squared),
        "actual_metric_energy_error_squared_upper_bound": str(anisotropic_upper_tail_squared),
        "strictly_decreases_after_level_zero": m == 0 or isotropic_tail_squared < F(1, 6) * F(1, 25) ** (m - 1),
    })
assert all(row["strictly_decreases_after_level_zero"] for row in tail_witness)
assert tail_witness[-1]["two_polarization_isotropic_energy_error_squared"] == str(F(1, 6) * F(1, 25) ** 8)

# Symbolic intertwiner witnesses.  For a coarse detail vector f,
# Delta_(m+1) J_m f = J_m Delta_m f exactly.  A deliberately non-refining
# comparator Delta_bad=Delta_good+P_coarse gives residual J_m f of unit norm.
intertwiner_witness = {
    "good_residual_norm_squared": "0",
    "bad_comparator_definition": "Delta_bad_(m+1)=Delta_good_(m+1)+P_coarse",
    "bad_residual_norm_squared_on_unit_coarse_detail": "1",
    "endpoint_has_dynamic_range": True,
}

# Source-boundary check is deliberately noncompensating.  BQGADM-011 states
# that refinement pullback is absent, and BGCE456 leaves the smooth symbol open.
physical_projector_refinement_present = "refinement pullback" not in bqgadm011["decisive_result"]
smooth_symbol_identified = bgce456["gate_decision"]["smooth_spacetime_principal_symbol_equal_to_A"] != "OPEN"
assert not physical_projector_refinement_present
assert not smooth_symbol_identified

theorem = {
    "finite_spaces": "H_m^phys=(I-E0)L2(C5^(3m)) tensor R^2 with normalized source trace",
    "finite_operator": "Delta_m^phys=Delta_m tensor I_2",
    "limit_operator": "The closure of sum_(k>=1) 25^k D_k tensor I_2 on the algebraic cylinder union; BGCE456 replaces the isotropic form by its positive equivalent actual-metric form.",
    "energy_space": "D(Delta^(1/2)) tensor R^2 direct_sum (I-E0)L2 tensor R^2",
    "wave_group": "W(t) generated by qdot=p, pdot=-Delta q",
    "exact_restriction": "W_(m+1)(t) J_m^phase=J_m^phase W_m(t) for every real t",
    "strong_convergence": "For the energy projection Q_m, sup_(t in R)||W(t)x-J_m^phase W_m(t)Q_m x||_E=||(I-Q_m)x||_E -> 0.",
    "two_mode_reason": "Tensoring the spatial operator and refinement isometry with I_2 preserves positivity, self-adjointness, exact intertwining and the energy estimate.",
}

endpoints = {
    "pinned_input_hashes": "PASS",
    "positive_selfadjoint_wave_operator": "PASS",
    "exact_refinement_intertwining": "PASS",
    "two_copy_energy_truncations_dense": "PASS_BY_EXACT_SPECTRAL_TAIL",
    "uniform_finite_time_strong_convergence": "PASS_EXACT_AND_IN_FACT_UNIFORM_FOR_ALL_REAL_TIME_IN_MEAN_ZERO_ENERGY_NORM",
    "actual_metric_extension": "PASS_BY_EXACT_POSITIVE_FORM_EQUIVALENCE_AND_REFINEMENT",
    "physical_ADM_projector_refinement_intertwiner": "OPEN_SOURCE_NOT_PRESENT",
    "smooth_Fierz_Pauli_principal_symbol_identity": "OPEN_SOURCE_NOT_PRESENT",
}

raw = {
    "schema": "siel.dpa.scout.bqgeuler004.raw.v1",
    "scout_id": "DPA-SCOUT-BQGEULER-004",
    "attempt": 1,
    "pinned_commit": manifest["pinned_commit"],
    "hash_checks": hash_checks,
    "source_facts": {
        "BGCE452_exact_refinement": bgce452["exact_refinement"]["intertwining"],
        "BGCE456_actual_metric_refinement": bgce456["isotropic_and_hierarchical_theorem"]["refinement"],
        "BGCE456_form_alpha": str(alpha),
        "BGCE456_form_beta": str(beta),
        "BQGADM011_physical_configuration_modes": 2,
        "BQGADM011_missing_refinement_pullback": True,
        "BGCE456_smooth_symbol_open": True,
    },
    "theorem": theorem,
    "tail_witness": tail_witness,
    "intertwiner_witness": intertwiner_witness,
    "endpoints": endpoints,
}

result = {
    "schema": "siel.dpa.scout.bqgeuler004.result.v1",
    "scout_id": "DPA-SCOUT-BQGEULER-004",
    "date": "2026-09-26",
    "work_package": "BQG-G3-R02.5",
    "primary_evidence_status": "Theoretical derivation",
    "secondary_qualifiers": [
        "exact inductive-limit wave theorem",
        "two-polarization hierarchical carrier",
        "physical-identification boundary"
    ],
    "decision": "CLOSED_SCOPED_HIERARCHICAL_TWO_MODE_ALL_TIME_STRONG_ENERGY_CONVERGENCE__OPEN_PHYSICAL_ADM_AND_SMOOTH_FIERZ_PAULI_IDENTIFICATION",
    "decisive_result": "Exact refinement intertwining makes every finite two-copy wave group the restriction of one inductive-limit wave group. Mean-zero finite-level projections converge in the wave-energy norm, and unitarity gives a uniform-in-time strong error equal to the initial energy-tail norm. BGCE456 exact positive form bounds extend this to the actual-metric hierarchical carrier. However, BQGADM-011 supplies only the two-mode quotient dimension and explicitly lacks a refinement pullback for the physical constraint ideal, while BGCE456 leaves equality with the smooth Fierz-Pauli principal symbol open. The theorem therefore closes the hierarchical two-copy dynamics, not physical ADM trajectory convergence.",
    "hierarchical_two_mode_strong_convergence": "CLOSED_SCOPED",
    "physical_ADM_two_mode_strong_convergence": "OPEN_SOURCE_IDENTIFICATION_REQUIRED",
    "smooth_continuum_target": "NOT_ESTABLISHED",
    "work_package_status_after_gate": "OPEN_SOURCE_CONSTRUCTION_REQUIRED",
    "next_minimum_gate": "DPA-SCOUT-BQGEULER-003_SOURCE_TYPED_NOETHER_KOSZUL_TATE_CONTRACTIBLE_FOUR_SCORE_GATE__PLUS_PHYSICAL_PROJECTOR_REFINEMENT_AND_SMOOTH_SYMBOL_INTERFACE",
    "formal_E0_E1_E2": "NOT_CLAIMED__BOUNDED_DPA_EXACT_THEORETICAL_SCOUT",
    "claim_ceiling": "Exact strong wave-trajectory convergence for two passive polarization copies of the BGCE452/BGCE456 mean-zero hierarchical source-cylinder carrier in its energy norm. No source-derived physical ADM projector/refinement intertwiner, smooth Fierz-Pauli generator identity, nonlinear Euler convergence, finite nonlinear HDA, empirical gravity, confirmation, RPD adoption, Level 3 or Official SIEL status."
}

(HERE / "RAW_OUTPUT.json").write_text(json.dumps(raw, ensure_ascii=False, indent=2) + "\n")
(HERE / "RESULT.json").write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n")
print(json.dumps({
    "scout_id": result["scout_id"],
    "decision": result["decision"],
    "hierarchical_two_mode": result["hierarchical_two_mode_strong_convergence"],
    "physical_ADM_two_mode": result["physical_ADM_two_mode_strong_convergence"],
    "work_package_status": result["work_package_status_after_gate"],
}, ensure_ascii=False, indent=2))
